# Generated by Django 3.0.5 on 2020-04-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDB',
            fields=[
                ('OrderID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('product', models.CharField(max_length=255)),
                ('date_regis', models.DateTimeField(verbose_name='Registed Date')),
                ('person', models.CharField(choices=[('cee', 'Wandee Angkura'), ('yui', 'aaa bbb')], max_length=8)),
            ],
        ),
    ]
